### ISSUE TITLE
Will there be an option to hide some columns on smaller screens?

### ISSUE THREAD

**Issue by OzanKurt** [matfish2/vue-tables#80] opened 2016-07-24 02:39 UTC
I am talking about this feature from [Datatables Responsive](https://datatables.net/extensions/responsive/examples/column-control/classes.html).

I think this feature could make many people choose vue-tables over Datatables.

**Comment by matfish2** [comment] 2016-07-24 05:27
Already implemented. Duplicate of #59.

**Closed by matfish2** 2016-07-24 05:27 UTC
