### ISSUE TITLE
Can I use custom select inside of the table?

### ISSUE THREAD

**Issue by lavezzi1** [matfish2/vue-tables#115] opened 2016-10-09 14:37 UTC
- Vue.js version: 1.0.28
- consumed using: webpack

Hello. Thanks for the great component!

I need to know, can I use custom select component like (https://josephuspaye.github.io/Keen-UI/#/ui-select-docs) in the table? 

My case: I have a lot if items, each item has unique id. So, I need to put the select with options like 'View', 'Edit', 'Delete' and so on. So data for this dropdown should looks like this:

```
dataDropdown: [
    {
        id: item.id,
        text: 'Edit',
        url: '/item/id/edit'
    },
    {
        id: item.id,
        text: 'Delete',
        url: '/item/id/delete'
    }
];
```

Is it possible? Thanks!

**Comment by matfish2** [comment] 2016-10-09 14:48
Well, as of now, there are three types of filters supported in the table itself: Plain text, select (on which you can apply select2), and date range picker.
In addition, you can use whatever filter you like outside the table and attach the query to through the `customFilters` option.

Allowing for other, user-defined types of filters in the table itself (i.e in the filters row, when `filterByColumn` is set to `true`) is something that I am currently contemplating and intend to implement in the near future.

In the meantime, you can use  a custom table template (passed as the third argument to the `Use` statement), or, if that isn't gonna cut it, fork the repo and make the necessary adjustments to support `ui-select`.

**Comment by matfish2** [comment] 2016-10-09 14:50
Do you mean as a filter, or as a column?

**Comment by lavezzi1** [comment] 2016-10-09 15:15
Please take a look at this example:

But instead of this default select I want to use custom dropdown like this https://josephuspaye.github.io/Keen-UI/#/ui-select-docs

So when I click on view or edit I'll go to the specific page. 
```
dataDropdown: [
    {
        id: item.id,
        text: 'Edit',
        url: '/item/id/edit'
    },
    {
        id: item.id,
        text: 'Delete',
        url: '/item/id/delete'
    }
];
```

![screen shot 2016-10-09 at 23 13 12](https://cloud.githubusercontent.com/assets/10686894/19221423/065581a4-8e76-11e6-8078-3248743920be.png)

**Comment by matfish2** [comment] 2016-10-09 15:21
You can use anything you want using the `templates` option and setting `compileTemplates` to `true`.

**Comment by lavezzi1** [comment] 2016-10-09 15:34
Yeah, but:

```
import Icon from '../components/icon';
var VueTables = require('vue-tables');
Vue.use(VueTables.client, {
    compileTemplates: true
});
```

```
        columns:['id','name','age', 'more'],
        tableData: [
            ...
        ],
        options: {
            templates: {
                more:'<icon icon="keyboard_arrow_down"></icon>'
            }
        }
```

Got error:
```
Unknown custom element: <icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

Yes, I registered it too, and it has a name.

**Comment by matfish2** [comment] 2016-10-09 15:48
Duplicate of #41

**Closed by matfish2** 2016-10-09 15:48 UTC

**Comment by lavezzi1** [comment] 2016-10-09 16:01
@matfish2 I am doing multiple page app, so each page has enry point (main.js) so it mean that I can not register my component globally right? I already tried that and it still doesn't work.

**Comment by matfish2** [comment] 2016-10-09 16:06
Why not? Simply include in each page:

`Vue.component('my-component', myComponent)`

Did you do that and still got the unregistered error?

**Comment by lavezzi1** [comment] 2016-10-10 03:47
@matfish2 Oh my mistake, yes it works. Now seems like it can't access the data, `<menu :options="arrayOptions"></menu` I did this and then pass the array with options in data. But it displays an empty menu. Whats wrong?

**Comment by lavezzi1** [comment] 2016-10-10 03:48
Outside of the table works fine.

**Comment by matfish2** [comment] 2016-10-10 06:25
Again, a scoping issue. You need to use `$parent`. In the docs.

**Comment by lavezzi1** [comment] 2016-10-10 08:14
@matfish2 Thanks. Can I use search outside of the table component? I didn't find anything about that in docs.

**Comment by matfish2** [comment] 2016-10-10 08:27
Yes. Use [`customFilters`](https://github.com/matfish2/vue-tables#custom-filters)

**Comment by lavezzi1** [comment] 2016-10-10 14:26
@matfish2 Please help. My template looks like this:
```
img: '<div class="image-status" :class="{ \'image-status--active\' : {active} }"><img class="image-status__icon" src="{url}" alt="{alt}"></div>',
```

`url` and `alt` works. But `{active}` doesn't. What I do wrong? 
Got error:
```
[Vue warn]: Invalid expression. Generated function body:  {'image-status--active':{scope.active}}
```

And is it possible to write data like this:
For example I got column called imageStatus
```
imageStatus: {
    url: 'https:/site.com/image.png',
    alt: 'alt',
    active: true
}
```
and then in component:
```
img: '<div class="image-status" :class="{ \'image-status--active\' : {imageStatus.active} }"><img class="image-status__icon" src="{imageStatus.url}" alt="{imageStatus.alt}"></div>',
```

**Comment by matfish2** [comment] 2016-10-10 15:42
For complex templates use a function instead of a string. See the `templates` option documentation, and the `age` column on the live demo.
Something like:

```js
{
   img: function(row) {

      let activeClass = row.active?'image-status--active':'';

       return `<div class="image-status ${activeClass}">
                     <img class="image-status__icon" 
                              src="${row.src}" 
                              alt="${row.alt}">
                    </div>`;
   }
```
}
