### ISSUE TITLE
Is multilevel json possible to use?

### ISSUE THREAD

**Issue by cboxdk** [matfish2/vue-tables#56] opened 2016-06-03 08:41 UTC
Is it possible to use data in from a multilevel/nested json?
It works great with a flat json response, but almost all our REST API's return a multilevel json like this:

`{"pagination":{"total":2,"per_page":10,"current_page":1,"last_page":1,"next_page_url":null,"prev_page_url":null},
"status":"success",
"data":[{"id":34,"name":"Company 1","vat":"","phone":"","email":"","note":"","web":"","userId":2,"teamId":2,"createdAt":"2016-06-02 17:15:08","updatedAt":"2016-06-02 17:15:08",
"team":{"id":2,"name":"EasyInspect ApS"},
"user":{"id":2,"name":"Sylvester Nielsen"},"inspections":[],"contacts":[],"addresses":[]},{"id":35,"name":"Company 2","vat":"","phone":"","email":"","note":"","web":"","userId":2,"teamId":2,"createdAt":"2016-06-02 17:15:43","updatedAt":"2016-06-02 17:15:43",
"team":{"id":2,"name":"EasyInspect ApS"},
"user":{"id":2,"name":"Sylvester Nielsen"},
"inspections":[],
"contacts":[],
"addresses":[]
}]
}`

**Comment by matfish2** [comment] 2016-06-03 13:42
Duplicate of #53

**Closed by matfish2** 2016-06-03 13:42 UTC
